export const METADATA_SELECTION = [
  "id didRadiantWin durationSeconds startDateTime endDateTime towerStatusRadiant towerStatusDire",
  "barracksStatusRadiant barracksStatusDire clusterId firstBloodTime lobbyType numHumanPlayers gameMode",
  "replaySalt isStats tournamentId tournamentRound actualRank averageRank averageImp parsedDateTime statsDateTime",
  "leagueId radiantTeamId direTeamId seriesId gameVersionId regionId sequenceNum rank bracket analysisOutcome",
  "predictedOutcomeWeight radiantNetworthLeads radiantExperienceLeads radiantKills direKills winRates",
  "predictedWinRates bottomLaneOutcome midLaneOutcome topLaneOutcome didRequestDownload league { id name banner",
  "basePrizePool stopSalesTime tier region private freeToSpectate startDateTime endDateTime tournamentUrl",
  "lastMatchDate hasLiveMatches prizePool imageUri displayName description country venue isFollowed } radiantTeam",
  "{ id name tag dateCreated isPro isLocked countryCode url logo baseLogo bannerLogo winCount lossCount",
  "lastMatchDateTime countryName coachSteamAccountId } direTeam { id name tag dateCreated isPro isLocked",
  "countryCode url logo baseLogo bannerLogo winCount lossCount lastMatchDateTime countryName coachSteamAccountId",
  "} series { id type teamOneId teamTwoId leagueId teamOneWinCount teamTwoWinCount winningTeamId",
  "lastMatchDateTime } pickBans { isPick heroId order bannedHeroId isRadiant playerIndex wasBannedSuccessfully",
  "isCaptain baseWinRate adjustedWinRate letter } towerStatus { towers { npcId hp } outposts { npcId",
  "isControlledByRadiant isRadiantSide } } laneReport { radiant { midLane { meleeCount rangeCount siegeCount",
  "denyCount neutralCount } offLane { meleeCount rangeCount siegeCount denyCount neutralCount } safeLane {",
  "meleeCount rangeCount siegeCount denyCount neutralCount } } dire { midLane { meleeCount rangeCount siegeCount",
  "denyCount neutralCount } offLane { meleeCount rangeCount siegeCount denyCount neutralCount } safeLane {",
  "meleeCount rangeCount siegeCount denyCount neutralCount } } } chatEvents { time type fromHeroId toHeroId value",
  "pausedTick isRadiant } towerDeaths { time npcId isRadiant attacker } spectators { steamId isRadiantCoach",
  "isVictory }",
].join(' ');

// The GraphQL relation graph is cyclic. This selection includes three object
// levels and then stops at scalar leaves, rather than traversing back into a
// match, team, series, or league indefinitely.
export const RELATIONS_SELECTION = [
  "league { id name banner basePrizePool stopSalesTime tier region private freeToSpectate startDateTime endDateTime",
  "tournamentUrl lastMatchDate hasLiveMatches prizePool imageUri displayName description country venue isFollowed",
  "nodeGroups { id name parentNodeGroupId advancingNodeGroupId advancingTeamCount teamCount defaultNodeType",
  "nodeGroupType round maxRounds isTieBreaker isFinalGroup isCompleted phase region startDate endDate",
  "secondaryAdvancingNodeGroupId secondaryAdvancingTeamCount tertiaryAdvancingNodeGroupId tertiaryAdvancingTeamCount",
  "eliminationDPCPoints nodes { nodeGroupId id name winningNodeId losingNodeId nodeType scheduledTime actualTime",
  "seriesId teamOneId teamTwoId teamOneWins teamTwoWins hasStarted isCompleted streamIds } } liveMatches { matchId",
  "radiantScore direScore leagueId delay spectators averageRank buildingState radiantLead lobbyId lobbyType",
  "serverSteamId gameTime completed isUpdating isParsing radiantTeamId direTeamId parseBeginGameTime numHumanPlayers",
  "gameMode gameState gameMinute players { matchId heroId name playerSlot steamAccountId isRadiant numKills",
  "numDeaths numAssists leaverStatus numLastHits numDenies goldPerMinute experiencePerMinute level gold goldSpent",
  "heroDamage towerDamage itemId0 itemId1 itemId2 itemId3 itemId4 itemId5 backpackId0 backpackId1 backpackId2",
  "networth respawnTimer ultimateCooldown ultimateState gameVersionId baseWinRateValue position } createdDateTime",
  "modifiedDateTime insight { teamOneVsWinCount teamTwoVsWinCount teamOneLeagueWinCount teamOneLeagueMatchCount",
  "teamTwoLeagueWinCount teamTwoLeagueMatchCount } winRateValues durationValues liveWinRateValues { time winRate } }",
  "series { id type teamOneId teamTwoId leagueId teamOneWinCount teamTwoWinCount winningTeamId lastMatchDateTime",
  "teamOne { id name tag dateCreated isPro isLocked countryCode url logo baseLogo bannerLogo winCount lossCount",
  "lastMatchDateTime countryName coachSteamAccountId } teamTwo { id name tag dateCreated isPro isLocked countryCode",
  "url logo baseLogo bannerLogo winCount lossCount lastMatchDateTime countryName coachSteamAccountId } node {",
  "nodeGroupId id name winningNodeId losingNodeId nodeType scheduledTime actualTime seriesId teamOneId teamTwoId",
  "teamOneWins teamTwoWins hasStarted isCompleted streamIds } } tables { leagueId tableTeams { teamId }",
  "tableHeroes { heroId } tablePlayers { steamAccountId } } battlePass { count average } stats { matchCount",
  "radiantWinMatchCount averageMatchDurationSeconds } prizePoolPercentages { leagueId index percentage } standings {",
  "leagueId teamId team { id name tag dateCreated isPro isLocked countryCode url logo baseLogo bannerLogo winCount",
  "lossCount lastMatchDateTime countryName coachSteamAccountId } standing prizeAmount } streams { id languageId name",
  "broadcastProvider streamUrl vodUrl } } radiantTeam { id name tag dateCreated isPro isLocked countryCode url logo",
  "baseLogo bannerLogo winCount lossCount lastMatchDateTime countryName coachSteamAccountId coachSteamAccount { id",
  "profileUri realName timeCreated countryCode stateCode cityId communityVisibleState name lastLogOff avatar",
  "primaryClanId isDotaPlusSubscriber dotaAccountLevel rankShift isAnonymous isStratzPublic seasonRank",
  "seasonLeaderboardRank seasonLeaderboardDivisionId proSteamAccount { id name realName fantasyRole teamId sponsor",
  "isLocked isPro totalEarnings birthday romanizedRealName roles aliases statuses twitterLink twitchLink",
  "instagramLink vkLink youTubeLink facebookLink weiboLink signatureHeroes position countries } activity { activity }",
  "smurfFlag lastMatchDateTime lastMatchRegionId battlepass { steamAccountId eventId level } guild { guildId",
  "steamAccountId joinDateTime matchCount winCount imp } isCaster } members { steamAccountId steamAccount { id",
  "profileUri realName timeCreated countryCode stateCode cityId communityVisibleState name lastLogOff avatar",
  "primaryClanId isDotaPlusSubscriber dotaAccountLevel rankShift isAnonymous isStratzPublic seasonRank",
  "seasonLeaderboardRank seasonLeaderboardDivisionId smurfFlag lastMatchDateTime lastMatchRegionId isCaster } player",
  "{ steamAccountId matchCount winCount imp firstMatchDate lastMatchDate lastMatchRegionId behaviorScore isFollowed }",
  "teamId firstMatchId firstMatchDateTime lastMatchId lastMatchDateTime } } direTeam { id name tag dateCreated isPro",
  "isLocked countryCode url logo baseLogo bannerLogo winCount lossCount lastMatchDateTime countryName",
  "coachSteamAccountId coachSteamAccount { id profileUri realName timeCreated countryCode stateCode cityId",
  "communityVisibleState name lastLogOff avatar primaryClanId isDotaPlusSubscriber dotaAccountLevel rankShift",
  "isAnonymous isStratzPublic seasonRank seasonLeaderboardRank seasonLeaderboardDivisionId proSteamAccount { id name",
  "realName fantasyRole teamId sponsor isLocked isPro totalEarnings birthday romanizedRealName roles aliases statuses",
  "twitterLink twitchLink instagramLink vkLink youTubeLink facebookLink weiboLink signatureHeroes position countries",
  "} activity { activity } smurfFlag lastMatchDateTime lastMatchRegionId battlepass { steamAccountId eventId level }",
  "guild { guildId steamAccountId joinDateTime matchCount winCount imp } isCaster } members { steamAccountId",
  "steamAccount { id profileUri realName timeCreated countryCode stateCode cityId communityVisibleState name",
  "lastLogOff avatar primaryClanId isDotaPlusSubscriber dotaAccountLevel rankShift isAnonymous isStratzPublic",
  "seasonRank seasonLeaderboardRank seasonLeaderboardDivisionId smurfFlag lastMatchDateTime lastMatchRegionId isCaster",
  "} player { steamAccountId matchCount winCount imp firstMatchDate lastMatchDate lastMatchRegionId behaviorScore",
  "isFollowed } teamId firstMatchId firstMatchDateTime lastMatchId lastMatchDateTime } } series { id type teamOneId",
  "teamTwoId leagueId teamOneWinCount teamTwoWinCount winningTeamId lastMatchDateTime teamOne { id name tag",
  "dateCreated isPro isLocked countryCode url logo baseLogo bannerLogo winCount lossCount lastMatchDateTime",
  "countryName coachSteamAccountId } teamTwo { id name tag dateCreated isPro isLocked countryCode url logo baseLogo",
  "bannerLogo winCount lossCount lastMatchDateTime countryName coachSteamAccountId } node { nodeGroupId id name",
  "winningNodeId losingNodeId nodeType scheduledTime actualTime seriesId teamOneId teamTwoId teamOneWins teamTwoWins",
  "hasStarted isCompleted streamIds } }",
].join(' ');

export const PLAYERS_SELECTION = [
  "matchId playerSlot steamAccountId steamAccount { id profileUri realName timeCreated countryCode stateCode cityId",
  "communityVisibleState name lastLogOff avatar primaryClanId isDotaPlusSubscriber dotaAccountLevel rankShift",
  "isAnonymous isStratzPublic seasonRank seasonLeaderboardRank seasonLeaderboardDivisionId smurfFlag",
  "lastMatchDateTime lastMatchRegionId isCaster } isRadiant isVictory heroId gameVersionId hero { id name",
  "displayName shortName aliases gameVersionId } kills deaths assists leaverStatus numLastHits numDenies",
  "goldPerMinute networth experiencePerMinute level gold goldSpent heroDamage towerDamage heroHealing partyId",
  "isRandom lane position streakPrediction intentionalFeeding role roleBasic imp award item0Id item1Id item2Id",
  "item3Id item4Id item5Id backpack0Id backpack1Id backpack2Id neutral0Id behavior heroAverage { heroId week time",
  "position bracketBasicIds matchCount remainingMatchCount winCount mvp topCore topSupport courierKills apm casts",
  "abilityCasts kills deaths assists networth xp cs dn neutrals heroDamage towerDamage physicalDamage",
  "magicalDamage physicalDamageReceived magicalDamageReceived tripleKill ultraKill rampage godLike goldPerMinute",
  "disableCount disableDuration stunCount stunDuration slowCount slowDuration healingSelf healingAllies",
  "invisibleCount runePower runeBounty level campsStacked supportGold purgeModifiers ancients teamKills goldLost",
  "goldFed buybackCount weakenCount weakenDuration physicalItemDamage magicalItemDamage healingItemSelf",
  "healingItemAllies xpFed pureDamageReceived attackDamage attackCount castDamage damageReceived damage",
  "pureDamage kDAAverage killContributionAverage stompWon stompLost comeBackWon comeBackLost } additionalUnit {",
  "item0Id item1Id item2Id item3Id item4Id item5Id backpack0Id backpack1Id backpack2Id neutral0Id } dotaPlus {",
  "heroId steamAccountId level totalActions createdDateTime steamAccount { id profileUri realName timeCreated",
  "countryCode stateCode cityId communityVisibleState name lastLogOff avatar primaryClanId isDotaPlusSubscriber",
  "dotaAccountLevel rankShift isAnonymous isStratzPublic seasonRank seasonLeaderboardRank",
  "seasonLeaderboardDivisionId smurfFlag lastMatchDateTime lastMatchRegionId isCaster } } abilities { abilityId",
  "time level gameVersionId abilityType { id name uri isTalent } isTalent } invisibleSeconds dotaPlusHeroXp variant",
].join(' ');

export const STATS_SELECTION = [
  "stats { matchId steamAccountId gameVersionId level killEvents { time target byAbility byItem gold xp positionX",
  "positionY assist isSolo isGank isInvisible isSmoke isTpRecently } deathEvents { time attacker target byAbility",
  "byItem goldFed xpFed timeDead positionX positionY goldLost assist isWardWalkThrough isAttemptTpOut isDieBack",
  "isBurst isEngagedOnDeath hasHealAvailable isTracked } assistEvents { time target gold xp positionX positionY }",
  "lastHitsPerMinute goldPerMinute experiencePerMinute healPerMinute heroDamagePerMinute towerDamagePerMinute",
  "towerDamageReport { npcId damage damageCreeps damageFromAbility } courierKills { time positionX positionY }",
  "wards { time type positionX positionY } itemPurchases { time itemId } itemUsed { itemId count } allTalks {",
  "time message pausedTick } chatWheels { time chatWheelId pauseTick } actionsPerMinute actionReport {",
  "moveToPosition moveToTarget attackPosition attackTarget castPosition castTarget castNoTarget heldPosition",
  "glyphCast scanUsed pingUsed } locationReport { positionX positionY } farmDistributionReport { creepType { id",
  "count gold xp } creepLocation { id count gold xp } neutralLocation { id count gold xp } ancientLocation { id",
  "count gold xp } buildings { id count gold xp } buyBackGold abandonGold bountyGold { id count gold xp } other {",
  "id count gold xp } } runes { time rune action gold positionX positionY } abilityCastReport { abilityId count",
  "targets { target count damage duration } } heroDamageReport { dealtTotal { physicalDamage magicalDamage",
  "pureDamage selfHeal allyHeal stunCount stunDuration disableCount disableDuration slowCount slowDuration }",
  "receivedTotal { physicalDamage magicalDamage pureDamage heal stunCount stunDuration disableCount",
  "disableDuration slowCount slowDuration } dealtTargets { target amount } receivedTargets { target amount }",
  "dealtSourceAbility { abilityId count amount } receivedSourceAbility { abilityId count amount } dealtSourceItem",
  "{ itemId count amount } receivedSourceItem { itemId count amount } } inventoryReport { item0 { itemId charges",
  "secondaryCharges } item1 { itemId charges secondaryCharges } item2 { itemId charges secondaryCharges } item3 {",
  "itemId charges secondaryCharges } item4 { itemId charges secondaryCharges } item5 { itemId charges",
  "secondaryCharges } backPack0 { itemId charges secondaryCharges } backPack1 { itemId charges secondaryCharges }",
  "backPack2 { itemId charges secondaryCharges } neutral0 { itemId charges secondaryCharges } } networthPerMinute",
  "campStack matchPlayerBuffEvent { time abilityId itemId stackCount } deniesPerMinute impPerMinute",
  "tripsFountainPerMinute spiritBearInventoryReport { item0Id item1Id item2Id item3Id item4Id item5Id backPack0Id",
  "backPack1Id backPack2Id neutral0Id } heroDamageReceivedPerMinute wardDestruction { time gold experience isWard",
  "} }",
].join(' ');

export const PLAYER_PLAYBACK_SELECTION = [
  "playbackData { abilityLearnEvents { time abilityId levelObtained level isUltimate isTalent isMaxLevel }",
  "abilityUsedEvents { time abilityId attacker target } abilityActiveLists { time ability0 ability1 ability2",
  "ability3 ability4 ability5 ability6 ability7 } itemUsedEvents { time itemId attacker target }",
  "playerUpdatePositionEvents { time x y } playerUpdateGoldEvents { time gold unreliableGold networth",
  "networthDifference } playerUpdateAttributeEvents { time agi int str } playerUpdateLevelEvents { time level }",
  "playerUpdateHealthEvents { time hp maxHp mp maxMp } playerUpdateBattleEvents { time damageMinMax damageBonus",
  "hpRegen mpRegen } killEvents { time attacker isFromIllusion target byAbility byItem gold xp positionX",
  "positionY assist isSolo isGank isInvisible isSmoke isTpRecently isRuneEffected } deathEvents { time attacker",
  "isFromIllusion target byAbility byItem goldFed xpFed timeDead reliableGold unreliableGold positionX positionY",
  "goldLost assist isWardWalkThrough isAttemptTpOut isDieBack isBurst isEngagedOnDeath hasHealAvailable isTracked",
  "isFeed } assistEvents { time attacker target gold xp subTime positionX positionY } csEvents { time attacker",
  "isFromIllusion npcId byAbility byItem gold xp positionX positionY isCreep isNeutral isAncient mapLocation }",
  "goldEvents { time amount reason npcId isValidForStats } experienceEvents { time amount reason positionX",
  "positionY } healEvents { time attacker target value byAbility byItem } heroDamageEvents { time attacker target",
  "value byAbility byItem damageType fromNpc toNpc fromIllusion toIllusion isPhysicalAttack isSourceMainHero",
  "isTargetMainHero } towerDamageEvents { time attacker npcId damage byAbility byItem fromNpc } inventoryEvents {",
  "time item0 { itemId charges secondaryCharges } item1 { itemId charges secondaryCharges } item2 { itemId",
  "charges secondaryCharges } item3 { itemId charges secondaryCharges } item4 { itemId charges secondaryCharges }",
  "item5 { itemId charges secondaryCharges } backPack0 { itemId charges secondaryCharges } backPack1 { itemId",
  "charges secondaryCharges } backPack2 { itemId charges secondaryCharges } teleport0 { itemId charges",
  "secondaryCharges } neutral0 { itemId charges secondaryCharges } } purchaseEvents { time itemId } buyBackEvents",
  "{ time heroId deathTimeRemaining cost } streakEvents { time heroId type value } runeEvents { time rune action",
  "gold positionX positionY } spiritBearInventoryEvents { time item0 { itemId } item1 { itemId } item2 { itemId }",
  "item3 { itemId } item4 { itemId } item5 { itemId } backPack0 { itemId } backPack1 { itemId } backPack2 {",
  "itemId } teleport0 { itemId } neutral0 { itemId } } }",
].join(' ');

export const PLAYBACK_SELECTION = [
  "playbackData { courierEvents { id ownerHero isRadiant events { time positionX positionY hp isFlying",
  "respawnTime didCastBoost item0Id item1Id item2Id item3Id item4Id item5Id } } runeEvents { indexId time",
  "positionX positionY location rune action } wardEvents { indexId time positionX positionY fromPlayer wardType",
  "action playerDestroyed } buildingEvents { time indexId type hp maxHp positionX positionY isRadiant npcId",
  "didShrineActivate } towerDeathEvents { time radiant dire } roshanEvents { time hp maxHp createTime x y",
  "totalDamageTaken item0 item1 item2 item3 item4 item5 } radiantCaptainHeroId direCaptainHeroId }",
].join(' ');
